-- Update passwords with correct bcrypt hashes (generated by application)

-- Admin User (password123)
UPDATE users 
SET password = '$2a$10$uYxZtKxy0scNyAblaHSxpe6u2zpw46raAJr/DNBZzrM4/1XpvHBe2'
WHERE dsa_unique_code = 'ADMIN001';

-- DSA User (password123)
UPDATE users 
SET password = '$2a$10$uYxZtKxy0scNyAblaHSxpe6u2zpw46raAJr/DNBZzrM4/1XpvHBe2'
WHERE dsa_unique_code = 'DSA_ACTIVE_001';
